### ISSUE TITLE
npm run start return errors

### ISSUE THREAD

**Issue by g-kartik** [Bwca/linkedin-learning-downloader#20]

**Comment by g-kartik** [comment]
Requesting video options for Why create containers using Docker?...
(node:26568) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/media/myunix/Storage/hack/linkedin-learning-downloader-master/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/media/myunix/Storage/hack/linkedin-learning-downloader-master/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/media/myunix/Storage/hack/linkedin-learning-downloader-master/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:26568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:26568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Bwca** [comment]
403 means you are authenticated, but not authorized to perform the requests. My guess is that you are logged in, but attempt to download videos that are behind some kind of lock, i.e. require premium to view. Downloader cannot bypass that, it cannot scrape videos you are not authorized to view.

**Comment by g-kartik** [comment]
However, I am a premium user.

**Comment by Bwca** [comment]
Okay, I think I've reproduced it, it could be a problem with the cookie you paste. Gonna look into it.

**Comment by Bwca** [comment]
Alright, tested it on an unlocked course, and it works.

The way I managed to reproduce your 403 was by deleting a part of the cookie string, so my guess is that something goes wrong during the copy/pasting. Are you using it from IDE terminal or just terminal? I had some issues with Visual Studio code messing up things when they are pasted.

I have updated the readme with instructions where to get the token and the cookie in the dev tools and also with instructions how to save them to files if you're using the compiled version. I think it should solve your issue.

**Comment by code-0802** [comment]
Thanks for updating the README, it works now. However, when I tried to save the csrf-token and cookie values in dist directory as .token file and run the program, I got the following error
`(node:8027) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["csrf-token"]`

**Comment by Bwca** [comment]
That's interesting, could it be that there is a line break in your `csrf.token` file? A line break in any of these files could cause error.

**Comment by studioab** [comment]
Any ideas what could be the issue? Thanks

```
Requesting video options for Get prepared for CCNA 200-301...
Success!
Requesting video options for What you should know...
Success!
Requesting video options for Network models...
Success!
Requesting video options for Network components...

Looks like something has gone wrong.
Failed with error: TypeError: Cannot read property 'videoPlay' of undefined
```

**Comment by Bwca** [comment]
Looks like linkedin video api result did not match their usual response model, could you provide the link to the course to reproduce the issue?

**Comment by studioab** [comment]
course url
https://www.linkedin.com/learning/cisco-ccna-200-301-cert-prep-network-fundamentals-and-access

fyi I have an access to premium courses and I've tried a bunch of them, nothing works even free one, app always fails after passing authentication and pulling metadata from the first 3 or 4 lessons

**Comment by Bwca** [comment]
Yes, I anticipated you have the rights to view the course, otherwise you wouldn't have been able to get metadata for any of the lessons. I tried reproducing it on https://www.linkedin.com/learning/react-creating-and-hosting-a-full-stack-site and it works. Guess I'll add some error handling and logging to parsing the videos metadata, that might cast some light at the problem.

**Comment by Bwca** [comment]
Alright, I've added a try catch block that'll pollute your console with the problematic response body if an error is encountered when parsing video responses from linkedin api, you can copy/paste it here once you reproduce the bug. Don't forget to pull latest change from master.

**Comment by studioab** [comment]
`https://www.linkedin.com/learning/cisco-ccna-200-301-cert-prep-network-fundamentals-and-access

Found 30 videos:

1. Get prepared for CCNA 200-301.
2. What you should know.
3. Network models.
4. Network components.
5. Network topology achitecture.
6. Physical interface and cable types.
7. Command-line interface.
8. Remote access.
9. Interface and cable issue troubleshooting.
10. TCP and UDP.
11. IPv4 addressing and subnetting.
12. Configuring IPv4 addressing.
13. Private IPv4 addressing and NAT.
14. Configure and verify IPv6 addressing and prefix.
15. IPv6 address types.
16. Verify IP parameters on client devices.
17. Virtualization fundamentals.
18. Switching concepts.
19. VLANs.
20. VLAN trunking.
21. Layer 2 discovery protocols.
22. EtherChannels.
23. Spanning tree protocol.
24. Wireless frequencies.
25. Wireless principles.
26. Wireless security.
27. Wireless architectures and AP modes.
28. AP connections and management protocols.
29. WLC client configuration.
30. Next steps.
Requesting video options for Get prepared for CCNA 200-301...
Success!
Requesting video options for What you should know...
Success!
Requesting video options for Network models...
Success!
Requesting video options for Network components...

Looks like something has gone wrong.
Failed with error: function toString() { [native code] }
Problematic videoResponse element:
 {"elements":[{"parent":"urn:li:learningApiCourse:4710269","visibility":"LOCKED","creators":[],"entityType":"VIDEO","activatedAt":1576195200000,"trackingUrn":"urn:li:lyndaVideo:(urn:li:lyndaCourse:2825029,2937283)","description":{"text":"This video explains the role and function of network components. This is important to understand the various hardware components used to build networks."},"primaryThumbnail":{"source":{"com.linkedin.common.VectorImage":{"digitalmediaAsset":"urn:li:digitalmediaAsset:C4E0DAQH1GYP-VjGYwQ","artifacts":[{"width":256,"fileIdentifyingUrlPathSegment":"144_256/0/1576263735532?e=1617814800&v=beta&t=TwofzNfHZRyzikiIGOC1phAMia95wwDe2EAuzGKExvw","expiresAt":1617814800000,"height":144},{"width":512,"fileIdentifyingUrlPathSegment":"288_512/0/1576263736316?e=1617814800&v=beta&t=X7CMbXODpkwVtItx-1M9N-pbDYlq8Y0MGrLaVuDbafM","expiresAt":1617814800000,"height":288},{"width":100,"fileIdentifyingUrlPathSegment":"60_100/0/1576263736581?e=1617814800&v=beta&t=gE372grmuaMDO0Vs_k-7-sWq_FzDCeCHHQX47knvFPU","expiresAt":1617814800000,"height":60},{"width":432,"fileIdentifyingUrlPathSegment":"240_432/0/1576263735322?e=1617814800&v=beta&t=TnumvH5NYRZmSrFOKbxtee_4phzJsG3GPuw8cl5v31w","expiresAt":1617814800000,"height":240},{"width":1200,"fileIdentifyingUrlPathSegment":"675_1200/0/1576263735997?e=1617814800&v=beta&t=bM98fqNXxX9nXP7GKL-o99FhFbFBQ794bR-1qV6wmX0","expiresAt":1617814800000,"height":675}],"rootUrl":"https://media-exp1.licdn.com/dms/image/C4E0DAQH1GYP-VjGYwQ/learning-public-crop_"}}},"title":"Network components","progressStateThresholds":{"metric":"MAX_OFFSET","completionThreshold":{"duration":50,"unit":"SECOND"},"inProgressThreshold":{"duration":5,"unit":"SECOND"}},"tags":[],"duration":{"duration":279,"unit":"SECOND"},"lifecycle":"ACTIVATED","skills":[],"features":{},"entityUrn":"urn:li:learningApiVideo:862325","cachingKey":"urn:li:learningApiVideo:862325","slug":"network-components","trackingId":"+4McE5xTTEG1FBN+teuDfg=="}],"paging":{"count":10,"start":0,"links":[]}}`

**Comment by Bwca** [comment]
Yep, it does look weird, the response model is different from what it's supposed to be, it doesn't have the presentation field where the video metadata is stored, the model of your response is to the right:

![image](https://user-images.githubusercontent.com/42136071/113750100-093b8300-9713-11eb-802f-8cffd54db98d.png)

**Comment by studioab** [comment]
are you able to download this course under your account?

**Comment by Bwca** [comment]
I would have done so instead of adding the logger lol
No, I'm currently on free membership, sorry :)

**Comment by studioab** [comment]
it reproes on my end with any free courses tho
